cart/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('' , cart_detail_view , name='cart_detail'),
    path('add/<int:product_id>/' , add_to_cart_view , name='add_to_cart'),
    path('remove/<int:product_id>/' , remove_from_cart_view , name='remove_from_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('' , include('pages.urls')),
    path('products/' , include('products.urls')),
    path('cart/' , include('cart.urls')),
    path('orders/' , include('orders.urls')),
    path('payment/' , include('payment.urls')),

    path('rosetta/', include('rosetta.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ debug_toolbar_urls()

pages/urls.py
from django.urls import path
from .views import Home_page , favorite_list_view , add_to_favorite_view ,remove_favorite_view


app_name = 'pages'

urlpatterns = [
    path('' , Home_page.as_view() , name='home_page'),
    # path('category/', HomePageView.as_view(), name='category'),
    path('favorites/', favorite_list_view, name='favorite_products'),
    path('favorites/add/<int:product_id>/', add_to_favorite_view, name='add_to_favorites'),
    path('favorites/remove/<int:product_id>/', remove_favorite_view, name='remove_from_favorites'),


]

pages/templates/pages/category_sort.html
{% load static %}
<nav class="nav-wrapper container">
    <ul>
        <li class="category-list">
            <a href="#">
                <i>
                    <svg width="20px" height="20px" viewBox="0 -1 12 12" id="meteor-icon-kit__regular-bars-s" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M0.85714 2C0.38376 2 0 1.55228 0 1C0 0.44772 0.38376 0 0.85714 0H11.1429C11.6162 0 12 0.44772 12 1C12 1.55228 11.6162 2 11.1429 2H0.85714zM0.85714 6C0.38376 6 0 5.5523 0 5C0 4.4477 0.38376 4 0.85714 4H11.1429C11.6162 4 12 4.4477 12 5C12 5.5523 11.6162 6 11.1429 6H0.85714zM0.85714 10C0.38376 10 0 9.5523 0 9C0 8.4477 0.38376 8 0.85714 8H11.1429C11.6162 8 12 8.4477 12 9C12 9.5523 11.6162 10 11.1429 10H0.85714z" fill="#758CA3"/></svg>
                </i>دسته بندی کالاها </a>
            <ul>
                {% for category in categories %}
                    <li>
                        <a href="{% url 'product_list' category.slug %}">{{ category.title }}</a>
                        <ul class="row">
                            <li class="col-3">
                                <a href="{% url 'product_list' category.slug %}">{{ category.title }}</a>
                                <ul>
                                    {% for sub_category in category.children.all  %}
                                        <li>
                                            <a href="{% url 'product_list' sub_category.slug %}">{{ sub_category.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </li>


        <li>
            <a href="#">
                <i></i>سوال دارید؟ </a>
        </li>
    </ul>

</nav>

pages/templates/pages/header.html
{% load static %}
{% load render_partial %}
<header class="page-header dt-sl">

    <div class="top-page-header">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between">
                <div class="contact-list">
                    <ul>
                        <li>
                            <svg width="23px" height="23px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path opacity="0.5" d="M10.0376 5.31617L10.6866 6.4791C11.2723 7.52858 11.0372 8.90532 10.1147 9.8278C10.1147 9.8278 10.1147 9.8278 10.1147 9.8278C10.1146 9.82792 8.99588 10.9468 11.0245 12.9755C13.0525 15.0035 14.1714 13.8861 14.1722 13.8853C14.1722 13.8853 14.1722 13.8853 14.1722 13.8853C15.0947 12.9628 16.4714 12.7277 17.5209 13.3134L18.6838 13.9624C20.2686 14.8468 20.4557 17.0692 19.0628 18.4622C18.2258 19.2992 17.2004 19.9505 16.0669 19.9934C14.1588 20.0658 10.9183 19.5829 7.6677 16.3323C4.41713 13.0817 3.93421 9.84122 4.00655 7.93309C4.04952 6.7996 4.7008 5.77423 5.53781 4.93723C6.93076 3.54428 9.15317 3.73144 10.0376 5.31617Z" fill="#1C274C"/>
                                <path d="M13.2595 1.87983C13.3257 1.47094 13.7122 1.19357 14.1211 1.25976C14.1464 1.26461 14.2279 1.27983 14.2705 1.28933C14.3559 1.30834 14.4749 1.33759 14.6233 1.38082C14.9201 1.46726 15.3347 1.60967 15.8323 1.8378C16.8286 2.29456 18.1544 3.09356 19.5302 4.46936C20.906 5.84516 21.705 7.17097 22.1617 8.16725C22.3899 8.66487 22.5323 9.07947 22.6187 9.37625C22.6619 9.52466 22.6912 9.64369 22.7102 9.72901C22.7197 9.77168 22.7267 9.80594 22.7315 9.83125L22.7373 9.86245C22.8034 10.2713 22.5286 10.6739 22.1197 10.7401C21.712 10.8061 21.3279 10.53 21.2601 10.1231C21.258 10.1121 21.2522 10.0828 21.2461 10.0551C21.2337 9.9997 21.2124 9.91188 21.1786 9.79572C21.1109 9.56339 20.9934 9.21806 20.7982 8.79238C20.4084 7.94207 19.7074 6.76789 18.4695 5.53002C17.2317 4.29216 16.0575 3.59117 15.2072 3.20134C14.7815 3.00618 14.4362 2.88865 14.2038 2.82097C14.0877 2.78714 13.9417 2.75363 13.8863 2.7413C13.4793 2.67347 13.1935 2.28755 13.2595 1.87983Z" fill="#1C274C"/>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M13.4857 5.3293C13.5995 4.93102 14.0146 4.7004 14.4129 4.81419L14.2069 5.53534C14.4129 4.81419 14.4129 4.81419 14.4129 4.81419L14.4144 4.81461L14.4159 4.81505L14.4192 4.81602L14.427 4.81834L14.4468 4.8245C14.4618 4.82932 14.4807 4.8356 14.5031 4.84357C14.548 4.85951 14.6074 4.88217 14.6802 4.91337C14.8259 4.97581 15.0249 5.07223 15.2695 5.21694C15.7589 5.50662 16.4271 5.9878 17.2121 6.77277C17.9971 7.55775 18.4782 8.22593 18.7679 8.7154C18.9126 8.95991 19.009 9.15897 19.0715 9.30466C19.1027 9.37746 19.1254 9.43682 19.1413 9.48173C19.1493 9.50418 19.1555 9.52301 19.1604 9.53809L19.1665 9.55788L19.1688 9.56563L19.1698 9.56896L19.1702 9.5705C19.1702 9.5705 19.1707 9.57194 18.4495 9.77798L19.1707 9.57194C19.2845 9.97021 19.0538 10.3853 18.6556 10.4991C18.2607 10.6119 17.8492 10.3862 17.7313 9.99413L17.7276 9.98335C17.7223 9.96832 17.7113 9.93874 17.6928 9.89554C17.6558 9.8092 17.5887 9.66797 17.4771 9.47938C17.2541 9.10264 16.8514 8.53339 16.1514 7.83343C15.4515 7.13348 14.8822 6.73078 14.5055 6.50781C14.3169 6.39619 14.1757 6.32909 14.0893 6.29209C14.0461 6.27358 14.0165 6.26254 14.0015 6.25721L13.9907 6.25352C13.5987 6.13564 13.3729 5.72419 13.4857 5.3293Z" fill="#1C274C"/>
                            </svg>
                            <a href="tel: 02100000000">021-00000000</a>
                        </li>
                        <li>
                            <svg width="22px" height="22px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="style=bulk">
                                    <g id="email">
                                        <path id="vector (Stroke)" fill-rule="evenodd" clip-rule="evenodd" d="M2.86466 4.1379C3.92465 3.15363 5.38503 2.75 7 2.75H17C18.615 2.75 20.0754 3.15363 21.1353 4.1379C22.2054 5.13152 22.75 6.60705 22.75 8.5V15.5C22.75 17.393 22.2054 18.8685 21.1353 19.8621C20.0754 20.8464 18.615 21.25 17 21.25H7C5.38503 21.25 3.92465 20.8464 2.86466 19.8621C1.79462 18.8685 1.25 17.393 1.25 15.5V8.5C1.25 6.60705 1.79462 5.13152 2.86466 4.1379Z" fill="#BFBFBF"/>
                                        <path id="vector (Stroke)_2" fill-rule="evenodd" clip-rule="evenodd" d="M19.3633 7.31026C19.6166 7.63802 19.5562 8.10904 19.2285 8.3623L13.6814 12.6486C12.691 13.4138 11.3089 13.4138 10.3185 12.6486L4.77144 8.3623C4.44367 8.10904 4.38328 7.63802 4.63655 7.31026C4.88982 6.98249 5.36083 6.9221 5.6886 7.17537L11.2356 11.4616C11.6858 11.8095 12.3141 11.8095 12.7642 11.4616L18.3113 7.17537C18.6391 6.9221 19.1101 6.98249 19.3633 7.31026Z" fill="#000000"/>
                                    </g>
                                </g>
                            </svg>
                            <a href="mailto: site@example.com">site@example.com</a>
                        </li>
                    </ul>
                </div>
                <div class="top-header-menu">
                    <ul>
                        <li>
                            <a href="{% url 'pages:home_page' %}"><i class="fad fa-home text-sm ml-1 "></i>خانه</a>
                        </li>
                        <li>
                            <a href="#"><i class="fad fa-shopping-basket text-sm ml-1 "></i>پیگیری سفارش</a>
                        </li>
                        <li>
                            <a href="{% url 'all-product-list' %}"><i class="fad fa-shopping-cart text-sm ml-1 "></i>فروشگاه</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="bottom-page-header">
            <div class="d-flex align-items-center">
                <div class="site-logo">
                    <a href="#">
                        <img src="{% static 'assets/img/svg/logo.svg' %}" alt="logo">
                    </a>
                </div>



                <div class="search-box">
                    <form  method="get" id="searchForm" action="{% url 'ajax_search_product' %}">
                        <input type="text" name="query" id="searchInput" placeholder="نام محصول یا برند را جستجو کنید..." autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
                        <button type="button">
                            <i>
                                <svg width="30px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path opacity="0.1" d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" fill="#323232"/>
                                    <path d="M15 15L21 21" stroke="#323232" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                    <path d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="#323232" stroke-width="2"/>
                                </svg>
                            </i>
                        </button>
                    </form>


                    <div class="search-result">
                        <ul class="search-result-list" id="results">
                           
                        </ul>

                    </div>
                </div>
            </div>


            <div class="user-items">
                <div class="user-item">
                    <a href="{% url 'pages:favorite_products' %}">
                        <svg width="23px" height="23px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path opacity="0.15" d="M4.3314 12.0474L12 20L19.6686 12.0474C20.5211 11.1633 21 9.96429 21 8.71405C21 6.11055 18.9648 4 16.4543 4C15.2487 4 14.0925 4.49666 13.24 5.38071L12 6.66667L10.76 5.38071C9.90749 4.49666 8.75128 4 7.54569 4C5.03517 4 3 6.11055 3 8.71405C3 9.96429 3.47892 11.1633 4.3314 12.0474Z" fill="#000000"/>
                            <path d="M4.3314 12.0474L12 20L19.6686 12.0474C20.5211 11.1633 21 9.96429 21 8.71405C21 6.11055 18.9648 4 16.4543 4C15.2487 4 14.0925 4.49666 13.24 5.38071L12 6.66667L10.76 5.38071C9.90749 4.49666 8.75128 4 7.54569 4C5.03517 4 3 6.11055 3 8.71405C3 9.96429 3.47892 11.1633 4.3314 12.0474Z" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <span class="bag-items-number">{{ favorites_count }}</span>
                    </a>
                </div>

                <div class="user-item cart-list">
                    <a href="#">
                        <svg width="25px" height="25px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path opacity="0.15" d="M3 10H21L19 20H5L3 10Z" fill="#000000"/>
                            <path d="M3 10H21M3 10L5 20H19L21 10M3 10L9 4M21 10L15 4" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <span class="bag-items-number">{{ cart|length }}</span>
                    </a>
                    {% include 'cart/cart_detail_side.html' %}
                </div>



                <div class="user-item account">

                    {% if user.is_authenticated %}
                        {% if user.first_name %}
                            <a href="#">{{ user.first_name }} {{  user.last_name  }} <i class="fad fa-chevron-down text-sm mr-1"></i>
                            </a>
                        {% else %}
                            <a href="#">{{ user.username }} <i class="fad fa-chevron-down text-sm mr-1"></i>
                            </a>
                        {% endif %}

                        <ul class="dropdown--wrapper">
                            <li class="header-profile-dropdown-account-container">
                                <a href="#" class="d-block">
                            <span class="header-profile-dropdown-user">
                                <span class="header-profile-dropdown-user-img">
                                <img src="{% static 'assets/img/avatar/avatar.png' %}">
                                </span>
                                {% if user.first_name %}
                                    <span class="header-profile-dropdown-user-info">
                                    <p class="header-profile-dropdown-user-name">{{ user.first_name }} {{  user.last_name  }} </p>
                                    <span class="header-profile-dropdown-user-profile-link">مشاهده حساب کاربری</span>
                                    </span>
                                {% else %}
                                    <span class="header-profile-dropdown-user-info">
                                    <p class="header-profile-dropdown-user-name">{{ user.username }} </p>
                                    <span class="header-profile-dropdown-user-profile-link">مشاهده حساب کاربری</span>
                                    </span>
                                {% endif %}
                            </span>
                                    <span class="header-profile-dropdown-account">
                                <span class="header-profile-dropdown-account-item">
                                <span class="header-profile-dropdown-account-item-title">اعتبار</span>
                                <span class="header-profile-dropdown-account-item-amount">
                                    <span class="header-profile-dropdown-account-item-amount-number">7,500,000</span> تومان </span>
                                </span>
                            </span>
                                </a>
                            </li>
                            <hr>
                            <li>
                                <a href="#"><i class="fad fa-clipboard-user text-sm ml-1 "></i> پروفایل </a>
                            </li>
                            <li>
                                <a href="#"><i class="fad fa-shopping-basket text-sm ml-1 "></i> پیگیری سفارش </a>
                            </li>
                            <li>
                                <a href="{% url 'account_logout' %}">   <i class="fad fa-portal-exit text-sm ml-1"></i>خروج از حساب    </a>
                            </li>
                        </ul>


                    {% else %}

                        <a href="{% url 'account_login' %}" class="btn-auth"><i class="fal fa-user-circle"></i>
                            ورود و عضویت
                        </a>
                    {% endif %}

                </div>
            </div>
        </div>



        
        {% render_partial 'pages.views.HomePageView' %}

    </div>
</header>